//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationbandaMusicales
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandasMusicales
    {
        public int id { get; set; }
        public string banda { get; set; }
        public string albums { get; set; }
        public string descripcion { get; set; }
        public string notas { get; set; }
        public byte[] ruta_foto { get; set; }
    }
}
